# Node.js

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(5be317d1-ce90-47cb-8ab6-2bbe753aa639)'
    appType: 'webAppLinux'
    WebAppName: 'smarthometunjic'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript